/**
 * Turns icons.json into React components.
 *
 * icons.json holds only the geometry. Attributes that every icon in the Figma
 * library shares — stroke 1.5, round cap and join, fill none — are omitted
 * there and re-applied here, so the data file stays small and a change to the
 * house style is a one-line edit.
 *
 *   node scripts/generate.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..");
const outDir = path.join(root, "src", "icons");

const { icons } = JSON.parse(fs.readFileSync(path.join(root, "icons.json"), "utf8"));

/** kebab-case → PascalCase, with a leading letter guaranteed. */
const pascal = (name) =>
  name
    .split(/[-_/\s]+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("")
    .replace(/^(\d)/, "Icon$1");

const attrsToJsx = (attrs) =>
  Object.entries(attrs)
    .map(([k, v]) => {
      // svg attribute → react prop
      const prop = k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
      return `${prop}="${v}"`;
    })
    .join(" ");

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

const names = Object.keys(icons).sort();
for (const name of names) {
  const comp = pascal(name);
  const body = icons[name]
    .map(([tag, attrs]) => {
      const a = attrsToJsx(attrs);
      return `    <${tag}${a ? " " + a : ""} />`;
    })
    .join("\n");

  fs.writeFileSync(
    path.join(outDir, `${comp}.tsx`),
    `// Generated from the Figma icon library — icon/${name}. Do not edit by hand.
import * as React from "react";
import { IconBase, type IconProps } from "../IconBase.js";

export const ${comp} = (props: IconProps) => (
  <IconBase {...props}>
${body}
  </IconBase>
);
${comp}.iconName = "${name}";
`
  );
}

fs.writeFileSync(
  path.join(root, "src", "index.ts"),
  `// Generated by scripts/generate.mjs — do not edit by hand.
export { IconBase, type IconProps } from "./IconBase.js";

${names.map((n) => `export { ${pascal(n)} } from "./icons/${pascal(n)}.js";`).join("\n")}

/** Every icon name in this package, as they are named in Figma. */
export const iconNames = [
${names.map((n) => `  "${n}",`).join("\n")}
] as const;
export type IconName = (typeof iconNames)[number];
`
);

console.log(`generated ${names.length} icons → src/icons/`);
