/**
 * Turns an official brand SVG into a component in src/brands/.
 *
 *   node scripts/import-brand.mjs google ~/Downloads/google-g.svg
 *   node scripts/import-brand.mjs github ~/Downloads/github-mark.svg
 *
 * Brand marks are not icons. The generated `icon/*` components go through
 * IconBase — one 24 grid, 1.5 stroke, currentColor — because that is how the
 * Figma icon library draws them. A brand mark is fixed multi-colour artwork
 * whose geometry and palette are set by the trademark owner, so these keep
 * their own viewBox and fills and are written out verbatim. Nothing here is
 * redrawn; whatever you point this at is what ships.
 *
 * Where the official files come from:
 *   Google     developers.google.com/identity/branding-guidelines  (signin-assets.zip)
 *   Apple      developer.apple.com/design/resources                (Sign in with Apple)
 *   GitHub     github.com/logos
 *   Microsoft  aka.ms/mssignin                                     (brand guidance pack)
 *
 * Each of those has usage rules — size, clear space, backgrounds, and whether
 * the mark may appear without its wordmark. They are worth reading before
 * placing the result.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const [, , rawName, file] = process.argv;
if (!rawName || !file) {
  console.error("usage: node scripts/import-brand.mjs <brand> <file.svg>");
  process.exit(1);
}
if (!fs.existsSync(file)) {
  console.error(`No such file: ${file}`);
  process.exit(1);
}

const here = path.dirname(fileURLToPath(import.meta.url));
const brandsDir = path.join(here, "..", "src", "brands");
fs.mkdirSync(brandsDir, { recursive: true });

const pascal = rawName
  .split(/[-_\s]+/)
  .map((s) => s[0].toUpperCase() + s.slice(1))
  .join("");

const svg = fs.readFileSync(file, "utf8");
const viewBox = (/viewBox="([^"]+)"/.exec(svg) || [, "0 0 24 24"])[1];
const inner = svg
  .replace(/<\?xml[\s\S]*?\?>/g, "")
  .replace(/<!--[\s\S]*?-->/g, "")
  .replace(/<svg[^>]*>/, "")
  .replace(/<\/svg>\s*$/, "")
  .trim()
  // JSX attribute names
  .replace(/([a-z]+)-([a-z])/g, (m, a, b) => `${a}${b.toUpperCase()}`)
  .replace(/class=/g, "className=")
  .replace(/\bxlink:href=/g, "xlinkHref=");

const out = `// Official ${pascal} brand mark, imported verbatim from the vendor's asset pack.
// Do not redraw or recolour — see scripts/import-brand.mjs for the sources and
// the usage rules that come with them.
import * as React from "react";

export interface BrandMarkProps extends Omit<React.SVGProps<SVGSVGElement>, "children"> {
  size?: number | string;
  title?: string;
}

export const ${pascal} = ({ size = "1em", title, ...props }: BrandMarkProps) => (
  <svg
    width={size}
    height={size}
    viewBox="${viewBox}"
    role={title ? "img" : undefined}
    aria-hidden={title ? undefined : true}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    {title ? <title>{title}</title> : null}
    ${inner.split("\n").join("\n    ")}
  </svg>
);
${pascal}.brandName = "${rawName}";
`;

const target = path.join(brandsDir, `${pascal}.tsx`);
fs.writeFileSync(target, out);

// Keep the barrel in step.
const barrel = path.join(brandsDir, "index.ts");
const names = fs
  .readdirSync(brandsDir)
  .filter((f) => f.endsWith(".tsx"))
  .map((f) => f.replace(/\.tsx$/, ""))
  .sort();
fs.writeFileSync(
  barrel,
  `// Generated by scripts/import-brand.mjs — do not edit by hand.\n` +
    names.map((n) => `export { ${n}, type BrandMarkProps } from "./${n}.js";`).join("\n") +
    "\n"
);

console.log(`wrote src/brands/${pascal}.tsx (viewBox ${viewBox})`);
console.log(`barrel now exports: ${names.join(", ")}`);
